api/urls.py
from django.urls import path
from .views import CompanyList, CompanyDetail, CommentList, CommentDetail, PedidoDetail, PedidoList

urlpatterns = [
    path('companies/<int:pk>/', CompanyDetail.as_view()),
    path('companies/', CompanyList.as_view()),
    path('comments/<int:pk>/', CommentDetail.as_view()),
    path('comments/', CommentList.as_view()),
    path('pedidos/<int:pk>/', PedidoDetail.as_view()),
    path('pedidos/', PedidoList.as_view()),
]

companies/urls.py
from django.urls import path
from .views import detail_company, list_companies,search_companies
from . import views
from user import views as vs
from user.models import User

app_name = 'companies'
urlpatterns = [
    path('', views.list_companies, name='list'),
    path('search/', views.search_companies, name= 'search'),
    path('<int:user_id>/', views.detail_company, name='detail'),
    path('update_company_profile/<int:user_id>/',vs.UpdateCompanyProfile.as_view(), name='update_company_profile'),
    path('<int:user_id>/pedido/', vs.create_pedido, name='create_pedido'),
    path('<int:comment_id>/reply/', vs.create_reply, name='create_reply'),
    path('<int:companyuser_id>/comment/', vs.create_comment, name='create_comment')
]

leva/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('landingpage.urls')),
    path('companies/', include('companies.urls')),
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('api/v1/', include('api.urls')),
]

companies/models.py
from django.db import models
from django.conf import settings

# Create your models here.

companies/views.py
from django.shortcuts import render
from django.http import HttpResponse
from user.models import Company, Pedido, Comment, Reply
from django.shortcuts import render, get_object_or_404
from django.db.models import Avg

# Create your views here

def detail_company(request, user_id):
    company = get_object_or_404(Company, user_id=user_id)
    pedidos_list = Pedido.objects.filter(company_id=user_id)
    comments_list = Comment.objects.all()
    replies_list = Reply.objects.all()
    context = {'company': company, 'pedidos_list': pedidos_list, 'comments_list': comments_list, 'replies_list' : replies_list,}
    return render(request, 'companies/detail.html', context)

def list_companies(request):
    city_list = Company.objects.order_by('city').values('city').distinct()
    job_list = Company.objects.order_by('job').values('job').distinct()
    company_list = Company.objects.annotate(avg_score=Avg('pedido__comments__score'))
    context = {
        'company_list': company_list,
        'job_list': job_list,
        'city_list': city_list,
    }
    return render(request, 'companies/list.html', context)

def is_valid_queryparam(param):
    return param != '' and param is not None

def search_companies(request):
    
    qs = Company.objects.annotate(avg_score=Avg('pedido__comments__score'))
    name_query = request.GET.get('query_name')
    city_query = request.GET.get('query_city')
    job_query = request.GET.get('query_job')
    score_query = request.GET.get('query_score')

    if is_valid_queryparam(name_query):
        qs = qs.filter(name__icontains=name_query)
    
    if is_valid_queryparam(city_query) and city_query != 'Cidade':
        qs = qs.filter(city__icontains=city_query)

    if is_valid_queryparam(job_query) and job_query != 'Serviço':
        qs = qs.filter(job__icontains=job_query)

    if is_valid_queryparam(score_query) and score_query != 'Avaliação':
        qs = qs.filter(avg_score__gte=score_query)

    context = {
        'company_list': qs
    }

    return render(request, 'companies/search.html', context)

companies/templates/companies/comment.html
{% extends 'base.html' %}


{% block content %}

<h2>Avalie o seu Pedido para {{ company.name }} </h2>


<form action="{% url 'companies:create_comment' company.user_id %}" method="post">

    {% csrf_token %}

    {{ form.as_p }}

    <button type="submit">Avaliar</button>

</form>


<p><a href="{% url 'companies:detail' company.user_id %}">Voltar para a página da empresa</a></p>

{% endblock content %}

companies/templates/companies/detail.html
{% extends 'base.html' %}

{% block title %}
{{company.user.name}}
{% endblock title %}

{% block content %}
<h2>{{company.name}}</h2>

<section class="dados-da-empresa">
    <img src={{ company.logoURL }} width="100"> </a> <br>
    <ul class="infos">
        <li><h3>Informações:</h3></li>
        <li>Cnpj: {{ company.cnpj }}</li>
        <li>Tel: {{ company.tel }}</li>
        <li>Job: {{ company.job }}</li>
        <li>Cidade: {{ company.city }}</li>
    </ul> <br>
    <h3>Avaliações</h3>
    <ul>{% if pedidos_list %}
        {% for comment in comments_list %}
            {% for pedido in pedidos_list %}
                {% if comment.pedido_id == pedido.id %}
                    <figure>
                        <blockquote>
                            "{{ comment.review }}". Nota: {{ comment.score }}
                        </blockquote>
                        <figcaption>— {{ comment.pedido.user.username }}
                            {% for reply in replies_list %}
                                {% if comment.pedido_id == reply.comment_id %}
                                <p> {{ reply.text }} - {{ company.name }} </p>
                                {% endif %}
                            {% endfor %}
                                {% if user.id == company.user.id %}
                                    <button><a href="{% url 'companies:create_reply' comment.pedido_id %}">Responda</a></button>
                                {% endif %}
                    </figure>
                {% endif %}
            {% endfor %}
        {% endfor %}
    {% endif %}</ul>
</section>

<section>
    <button><a href="{% url 'companies:create_pedido' company.user_id %}">Faça seu pedido de orçamento</a></button>
    {% if user.is_authenticated%}
        {% if user.is_client %} <!-- Se for cliente -->
        <button><a href="{% url 'companies:create_comment' company.user.id  %}">Avalie seu pedido</a></button>
        {% endif %}

        {% if user.id == company.user.id %} <!-- Se for a propria companhia -->
            <br><h2>Pedidos</h2> <br>
            {% if pedido_list %}
                <small>Você ainda não recebeu pedidos</small>
            {% else %}
            {% for pedido in pedidos_list %}
                <strong>{{ pedido.user.username }}</strong> <small>-{{ pedido.datetime }} </small>
                {{ pedido.body }} <br> <br>
            {% endfor %}
            {% endif %}

        <button><a href="{% url 'companies:update_company_profile' user.id %}">Altere seu perfil</a></button>
        {% endif %}
    {% endif %}
</section>

{% endblock content %}

companies/templates/companies/list.html
{% extends 'base.html' %}

{% block content %}
<h2>Todas as Empresas</h2> <br>
<section>
    <p>Muitos resultados?</p> <br>
</section>
<form action="{% url 'companies:search' %}">
    <p>
        <input type="text" name="query_name" id="id_query" placeholder="Nome da Empresa"/>
        <select id="id_query_city" name="query_city">
            <option selected>Cidade</option>
            {% for city in city_list %}
            <option value="{{ city.city }}">{{ city.city }}</option>
            {% endfor %}
        </select>
        <select id="id_query_job" name="query_job">
            <option selected>Serviço</option>
            {% for job in job_list %}
            <option value="{{ job.job }}">{{ job.job }}</option>
            {% endfor %}
        </select>
        <select id="id_query_score" name="query_score">
            <option selected>Avaliação</option>
            <option value="0.0">0</option>
            <option value="1.0">1</option>
            <option value="2.0">2</option>
            <option value="3.0">3</option>
            <option value="4.0">4</option>
            <option value="5.0">5</option>
            <option value="6.0">6</option>
            <option value="7.0">7</option>
            <option value="8.0">8</option>
            <option value="9.0">9</option>
            <option value="10.0">10</option>
        </select>
    </p> <br>
    <button type="submit">Filtrar</button>
</form>
{% if company_list %}
<section class="lista-de-cards">
    {% for company in company_list %}
    <article class="card">
        <a href="{% url 'companies:detail' company.user_id %}">{{company.name}}</a>
        <p>Avaliação: {{ company.avg_score }}</p>
        <p>CNPJ: {{ company.cnpj }}</p>
        <p>Cidade Sede: {{ company.city }}</p>
        <p>Serviço: {{ company.job }}</p>
    </article>
    {% endfor %}
</section>
{% else %}
<p>Não foi encontrado nenhuma empresa.</p>
{% endif %}

{% endblock content %}

companies/templates/companies/pedido.html
{% extends 'base.html' %}


{% block content %}

<h2>Pedido de Orçamento para {{ company.name }} </h2> 
<p class="text"> Escreva uma mensagem especificando a data de mudança e endereços de saída e chegada. Não se esqueça de deixar seu contato!</p>
    
    
    <form action="{% url 'companies:create_pedido' company.user_id %}" method="post">
        
        {% csrf_token %}
        
        {{ form.as_p }}
        
        <button type="submit">Fazer Pedido</button>
        
    </form>
    
    
    <p><a href="{% url 'companies:detail' company.user_id %}">Voltar para a página da empresa</a></p>

{% endblock content %}

companies/templates/companies/reply.html
{% extends 'base.html' %}


{% block content %}

<h2> Resposta para {{ pedido.user.username }} </h2>
<p>Avaliação: {{ comment.review }}<br>
    Nota: {{comment.score}}
</p>


<form action="{% url 'companies:create_reply' pedido.id %}" method="post">

    {% csrf_token %}

    {{ form.as_p }}

    <button type="submit">Responder</button>

</form>


<p><a href="{% url 'companies:detail' company.user_id %}">Voltar para a página da empresa</a></p>

{% endblock content %}

companies/templates/companies/search.html
{% extends 'base.html' %}

{% block content %}


<h2>Resultado da Busca</h2>
{% if company_list %}
<section class="lista-de-cards">
    {% for company in company_list %}
    <article class="card">
        <a href="{% url 'companies:detail' company.user_id %}">{{company.name}}</a>
        <p>Avaliação: {{ company.avg_score }}</p>
        <p>CNPJ: {{ company.cnpj }}</p>
        <p>Cidade: {{ company.city }}</p>
    </article>
    {% endfor %}
</section>
{% else %}
<p>Não foi encontrado nenhuma empresa.</p>
{% endif %}

{% endblock content %}