api/urls.py
from django.urls import path
from .views import CompanyList, CompanyDetail, CommentList, CommentDetail, PedidoDetail, PedidoList

urlpatterns = [
    path('companies/<int:pk>/', CompanyDetail.as_view()),
    path('companies/', CompanyList.as_view()),
    path('comments/<int:pk>/', CommentDetail.as_view()),
    path('comments/', CommentList.as_view()),
    path('pedidos/<int:pk>/', PedidoDetail.as_view()),
    path('pedidos/', PedidoList.as_view()),
]

companies/urls.py
from django.urls import path
from .views import detail_company, list_companies,search_companies
from . import views
from user import views as vs
from user.models import User

app_name = 'companies'
urlpatterns = [
    path('', views.list_companies, name='list'),
    path('search/', views.search_companies, name= 'search'),
    path('<int:user_id>/', views.detail_company, name='detail'),
    path('update_company_profile/<int:user_id>/',vs.UpdateCompanyProfile.as_view(), name='update_company_profile'),
    path('<int:user_id>/pedido/', vs.create_pedido, name='create_pedido'),
    path('<int:comment_id>/reply/', vs.create_reply, name='create_reply'),
    path('<int:companyuser_id>/comment/', vs.create_comment, name='create_comment')
]

leva/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('landingpage.urls')),
    path('companies/', include('companies.urls')),
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('api/v1/', include('api.urls')),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %} Leva-lá {% endblock %}
    </title>
    <link rel="shortcut icon" href="{% static 'logo.png' %}">
    <link href="https://fonts.googleapis.com/css?family=Inter&display=swap" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
</head>

<body>
    <header id="cabecalho-principal">
        <a href="{% url 'index' %}"> <img src="{% static 'levala branco.png' %}" width="100"> </a>
        <h1> &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp levaLá</h1>
        <nav id="navegacao-principal">
            {% if user.is_authenticated%}
            <li>Bem vindo {{ user.username }}</li>
            <li><a href="{% url 'logout' %}">Logout</a></li>
            <li><a href="{% url 'companies:list' %}">Buscar empresas</a></li>
                {% if user.is_client %}
                <li><a href="{% url 'profile' user.id %}">Perfil</a></li>
                {% endif %}
                {% if user.is_company %}
                <li><a href="{% url 'companies:detail' user.id %}">Página da Empresa</a></li>
                {% endif %}
            {% else %}
            <li><a href="{% url 'register' %}">Registrar</a></li>
            <li><a href="{% url 'login' %}">Login</a> </li>
            <li><a href="{% url 'companies:list' %}">Buscar empresas</a></li>
            {% endif %}
        </nav>

    </header>
    <main id="conteiner-principal">
        {% block content %}
        {% endblock content %}
    </main>
    <footer id="rodape-principal">
        <p>
            <small>Copyright 2022</small>
        </p>
    </footer>
</body>

</html>